version: "3.5"
services:
  go-api:
    container_name: go-api
    build:
      context: ./go
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - database
    ports:
      - 3333:3333
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1GB"

  node-api:
    container_name: node-api
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3332:3333
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1GB"

  database: # Banco de dados
    image: postgres:latest
    container_name: database
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=benchmark
